models/Client.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%client}}".
 *
 * @property int $id
 * @property int $iin
 * @property string $name
 * @property string $secondname
 * @property int $sex
 * @property string $birthdate
 *
 * @property array $sexList
 * @property Deposit[] $deposits
 */
class Client extends \yii\db\ActiveRecord
{
    const SEX_MALE = 1,
        SEX_FEMALE = 2;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%client}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['iin', 'name', 'secondname', 'sex', 'birthdate'], 'required'],
            [['iin', 'sex'], 'integer'],
            [['birthdate'], 'safe'],
            [['name', 'secondname'], 'string', 'max' => 64],
            [['iin'], 'unique'],
            [['sex'], 'in', 'range' => [self::SEX_MALE, self::SEX_FEMALE]],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'iin' => 'Iin',
            'name' => 'Name',
            'secondname' => 'Secondname',
            'sex' => 'Sex',
            'birthdate' => 'Birthdate',
        ];
    }

    public function getSexList()
    {
        return [
            self::SEX_MALE => 'Male',
            self::SEX_FEMALE => 'Female',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDeposits()
    {
        return $this->hasMany(Deposit::className(), ['client_id' => 'id']);
    }
}

controllers/ClientController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Client;
use app\models\search\Client as ClientSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Client model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/DepositController.php
<?php

namespace app\controllers;

use app\models\Client;
use app\models\DepositHistory;
use Yii;
use app\models\Deposit;
use app\models\search\Deposit as DepositSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DepositController implements the CRUD actions for Deposit model.
 */
class DepositController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Displays a single Deposit model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Deposit model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Deposit();
        $model->client_id = Yii::$app->request->get('client_id');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Deposit model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionTest()
    {
        $depositsQ = Deposit::find();

        /** @var Deposit $deposit */
        foreach ($depositsQ->each() as $deposit) {
            try {
                $transaction = Yii::$app->db->beginTransaction();
                $deposit->accruePercent();
                $deposit->accrueCommission();
                $transaction->commit();
            } catch (ErrorException $e) {
                $transaction->rollBack();
            }
        }

        return $this->render('test');
    }

    public function actionReport()
    {
        $percents = DepositHistory::find()
            ->select(['amount'=>'SUM(amount)', 'created_at_formatted'=>'DATE_FORMAT(FROM_UNIXTIME(`created_at`), "%Y-%m")'])
            ->where(['action' => DepositHistory::ACTION_ACCRUE])
            ->groupBy('created_at_formatted')
            ->orderBy(['created_at_formatted' => SORT_DESC])
            ->asArray()->all();

        $commissions = DepositHistory::find()
            ->select(['amount'=>'SUM(amount)', 'created_at_formatted'=>'DATE_FORMAT(FROM_UNIXTIME(`created_at`), "%Y-%m")'])
            ->where(['action' => DepositHistory::ACTION_COMMISSION])
            ->groupBy('created_at_formatted')
            ->orderBy(['created_at_formatted' => SORT_DESC])
            ->asArray()->all();

        $age18 = date('Y-m-d', strtotime('-18years'));
        $age25 = date('Y-m-d', strtotime('-25years'));
        $age50 = date('Y-m-d', strtotime('-50years'));

        $ageStatistics18_25 = Client::find()
            ->from('{{%client}} c')
            ->select(['averageVal' => 'AVG(d.amount)'])
            ->where(['and', ['>', 'birthdate', $age25], ['<=', 'birthdate', $age18]])
            ->leftJoin('{{%deposit}} d', 'c.id = d.client_id')
            ->scalar();

        $ageStatistics25_50 = Client::find()
            ->from('{{%client}} c')
            ->select(['averageVal' => 'AVG(d.amount)'])
            ->where(['and', ['>', 'birthdate', $age50], ['<=', 'birthdate', $age25]])
            ->leftJoin('{{%deposit}} d', 'c.id = d.client_id')
            ->scalar();

        $ageStatistics50 = Client::find()
            ->from('{{%client}} c')
            ->select(['averageVal' => 'AVG(d.amount)'])
            ->where(['<=', 'birthdate', $age50])
            ->leftJoin('{{%deposit}} d', 'c.id = d.client_id')
            ->scalar();
        return $this->render('report', [
            'percents' => $percents,
            'commissions' => $commissions,
            'ageStatistics18_25' => $ageStatistics18_25,
            'ageStatistics25_50' => $ageStatistics25_50,
            'ageStatistics50' => $ageStatistics50,
            ]);
    }

    /**
     * Finds the Deposit model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Deposit the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Deposit::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/client/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Client */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="client-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'iin')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'secondname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'sex')->dropDownList($model->sexList, ['prompt' => 'Select from list']) ?>

    <?= $form->field($model, 'birthdate')->textInput(['type' => 'date']) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/client/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\Client */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'iin') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'secondname') ?>

    <?= $form->field($model, 'sex') ?>

    <?php // echo $form->field($model, 'birthdate') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/client/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = 'Create Client';
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/client/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\Client */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Clients';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Client', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'iin',
            'name',
            'secondname',
            'sex',
            //'birthdate',

            [
				'class' => 'yii\grid\ActionColumn',
				'template' => '{view} {update}',
			],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/client/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = 'Update Client: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="client-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/client/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'iin',
            'name',
            'secondname',
            'sex',
            'birthdate',
        ],
    ]) ?>


	<p>
        <?= Html::a('Create Deposit', ['deposit/create', 'client_id' => $model->id], ['class' => 'btn btn-success']) ?>
	</p>

    <?= \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ArrayDataProvider([
			'allModels' => $model->deposits,
			'sort' => [
                'attributes' => ['amount', 'percent', 'created_at'],
			],
		]),
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'amount',
            'percent',
            'created_at:date',

			[
				'content' => function($data){
    				return Html::a(Html::tag('span', '', ['class' => "glyphicon glyphicon-eye-open"]), ['deposit/view', 'id' => $data->id]);
				},
				'format' => 'html',
			],
        ],
    ]); ?>

</div>