models/Deposit.php
<?php

namespace app\models;

use Yii;
use yii\base\ErrorException;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%deposit}}".
 *
 * @property int $id
 * @property int $client_id
 * @property double $amount
 * @property double $percent
 * @property int $created_at
 *
 * @property Client $client
 * @property DepositHistory[] $depositHistories
 */
class Deposit extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%deposit}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['client_id', 'amount', 'percent'], 'required'],
            [['client_id'], 'integer'],
            [['amount', 'percent'], 'number'],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Client::className(), 'targetAttribute' => ['client_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'client_id' => 'Client ID',
            'amount' => 'Amount',
            'percent' => 'Percent',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepositHistories()
    {
        return $this->hasMany(DepositHistory::className(), ['deposit_id' => 'id']);
    }

    public function getAccrueRate()
    {
        return $this->amount * $this->percent / 100;
    }

    public function getCommissionRate()
    {
        if ($this->amount < 1000) {
            $rate = 0.05;
        } elseif ($this->amount < 10000) {
            $rate = 0.06;
        } else {
            $rate = 0.07;
        }
        return $rate;
    }

    public function getCommission()
    {
        $commission = $this->amount * $this->getCommissionRate();
        if ($commission < 50) {
            $commission = 50;
        } elseif ($commission > 5000) {
            $commission = 5000;
        }

        if (strtotime(date('Y-m-d') . ' +1month') > time()) {
            $diff = (int)round((time() - $this->created_at) / (60 * 60 * 24));
            if ($diff === 0) {
                $commission = 0;
            } else {
                $commission = $commission / $diff;
            }
        }

        return $commission;
    }

    public function accruePercent()
    {
        $transaction = Yii::$app->db->beginTransaction();
        $this->amount += $this->getAccrueRate();
        if  ($this->save() && $this->addHistory(DepositHistory::ACTION_ACCRUE, $this->getAccrueRate())) {
            $transaction->commit();
            return true;
        } else {
            $transaction->rollBack();
            throw new ErrorException('Amount does not change.');
        }
    }

    public function accrueCommission()
    {
        $transaction = Yii::$app->db->beginTransaction();
        $this->amount -= $this->getCommission();
        if  ($this->save() && $this->addHistory(DepositHistory::ACTION_COMMISSION, $this->getCommission())) {
            $transaction->commit();
            return true;
        } else {
            $transaction->rollBack();
            throw new ErrorException('Amount does not change.');
        }
    }

    /**
     * @param $action
     * @param float $amount
     * @return bool
     * @throws ErrorException
     */
    public function addHistory($action, float $amount)
    {
        if ($this->isNewRecord) {
            throw new ErrorException('You should save deposit before.');
        }
        $history = new DepositHistory();
        $history->deposit_id = $this->id;
        $history->action = $action;
        $history->amount = $amount;
        return $history->save();
    }
}

controllers/ClientController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Client;
use app\models\search\Client as ClientSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Client model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/DepositController.php
<?php

namespace app\controllers;

use app\models\Client;
use app\models\DepositHistory;
use Yii;
use app\models\Deposit;
use app\models\search\Deposit as DepositSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DepositController implements the CRUD actions for Deposit model.
 */
class DepositController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Displays a single Deposit model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Deposit model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Deposit();
        $model->client_id = Yii::$app->request->get('client_id');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Deposit model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionTest()
    {
        $depositsQ = Deposit::find();

        /** @var Deposit $deposit */
        foreach ($depositsQ->each() as $deposit) {
            try {
                $transaction = Yii::$app->db->beginTransaction();
                $deposit->accruePercent();
                $deposit->accrueCommission();
                $transaction->commit();
            } catch (ErrorException $e) {
                $transaction->rollBack();
            }
        }

        return $this->render('test');
    }

    public function actionReport()
    {
        $percents = DepositHistory::find()
            ->select(['amount'=>'SUM(amount)', 'created_at_formatted'=>'DATE_FORMAT(FROM_UNIXTIME(`created_at`), "%Y-%m")'])
            ->where(['action' => DepositHistory::ACTION_ACCRUE])
            ->groupBy('created_at_formatted')
            ->orderBy(['created_at_formatted' => SORT_DESC])
            ->asArray()->all();

        $commissions = DepositHistory::find()
            ->select(['amount'=>'SUM(amount)', 'created_at_formatted'=>'DATE_FORMAT(FROM_UNIXTIME(`created_at`), "%Y-%m")'])
            ->where(['action' => DepositHistory::ACTION_COMMISSION])
            ->groupBy('created_at_formatted')
            ->orderBy(['created_at_formatted' => SORT_DESC])
            ->asArray()->all();

        $age18 = date('Y-m-d', strtotime('-18years'));
        $age25 = date('Y-m-d', strtotime('-25years'));
        $age50 = date('Y-m-d', strtotime('-50years'));

        $ageStatistics18_25 = Client::find()
            ->from('{{%client}} c')
            ->select(['averageVal' => 'AVG(d.amount)'])
            ->where(['and', ['>', 'birthdate', $age25], ['<=', 'birthdate', $age18]])
            ->leftJoin('{{%deposit}} d', 'c.id = d.client_id')
            ->scalar();

        $ageStatistics25_50 = Client::find()
            ->from('{{%client}} c')
            ->select(['averageVal' => 'AVG(d.amount)'])
            ->where(['and', ['>', 'birthdate', $age50], ['<=', 'birthdate', $age25]])
            ->leftJoin('{{%deposit}} d', 'c.id = d.client_id')
            ->scalar();

        $ageStatistics50 = Client::find()
            ->from('{{%client}} c')
            ->select(['averageVal' => 'AVG(d.amount)'])
            ->where(['<=', 'birthdate', $age50])
            ->leftJoin('{{%deposit}} d', 'c.id = d.client_id')
            ->scalar();
        return $this->render('report', [
            'percents' => $percents,
            'commissions' => $commissions,
            'ageStatistics18_25' => $ageStatistics18_25,
            'ageStatistics25_50' => $ageStatistics25_50,
            'ageStatistics50' => $ageStatistics50,
            ]);
    }

    /**
     * Finds the Deposit model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Deposit the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Deposit::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/deposit/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Deposit */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="deposit-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'client_id')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'amount')->textInput() ?>

    <?= $form->field($model, 'percent')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/deposit/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Deposit */

$this->title = 'Create Deposit';
$this->params['breadcrumbs'][] = ['label' => $model->client->name, 'url' => ['client/view', 'id' => $model->client->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="deposit-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/deposit/report.php
<?php
/**
 * @var \yii\web\View $this
 * @var array $percents
 * @var array $commission
 * @var float $ageStatistics18_25
 * @var float $ageStatistics25_50
 * @var float $ageStatistics50
 */
?>

<table class="table table-bordered table-striped table-hover">
    <tr>
        <th colspan="2">
            Начислено процентов пользователям (убыток банка)
        </th>
    </tr>
    <tr>
        <th>
            месяц
        </th>
        <th>
            сумма
        </th>
    </tr>
    <?php $percentsSum = 0; ?>
    <?php foreach ($percents as $item): ?>
        <tr>
            <td><?= $item['created_at_formatted']?></td>
            <td><?= $item['amount']?></td>
        </tr>
    <?php $percentsSum += $item['amount']; ?>
    <?php endforeach; ?>

    <tr>
        <th>
            итого:
        </th>
        <th>
            <?= $percentsSum; ?>
        </th>
    </tr>
</table>


<table class="table table-bordered table-striped table-hover">
    <tr>
        <th colspan="2">
            Снятия комисии (прибыль банка)
        </th>
    </tr>
    <tr>
        <th>
            месяц
        </th>
        <th>
            сумма
        </th>
    </tr>
    <?php $commissionsSum = 0; ?>
    <?php foreach ($commissions as $item): ?>
        <tr>
            <td><?= $item['created_at_formatted']?></td>
            <td><?= $item['amount']?></td>
        </tr>
    <?php $commissionsSum += $item['amount']; ?>
    <?php endforeach; ?>

    <tr>
        <th>
            итого:
        </th>
        <th>
            <?= $commissionsSum; ?>
        </th>
    </tr>
</table>


<table class="table table-bordered table-striped table-hover">
    <tr>
        <th colspan="3">
            Средний размер депозита
        </th>
    </tr>
    <tr>
        <th>
            18 - 25
        </th>
        <th>
            25 - 50
        </th>
        <th>
            50+
        </th>
    </tr>
    <tr>
        <td><?= $ageStatistics18_25; ?></td>
        <td><?= $ageStatistics25_50; ?></td>
        <td><?= $ageStatistics50; ?></td>
    </tr>
</table>

views/deposit/test.php
<p>
    Добавляет процент и снимет комиссию без учета даты
</p>

views/deposit/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Deposit */

$this->title = 'Update Deposit: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => $model->client->name, 'url' => ['client/view', 'id' => $model->client->id]];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="deposit-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/deposit/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Deposit */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => $model->client->name, 'url' => ['client/view', 'id' => $model->client->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="deposit-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'client_id',
            'amount',
            'percent',
            'created_at:datetime',
        ],
    ]) ?>

    <?= \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ArrayDataProvider([
            'allModels' => $model->depositHistories,
            'sort' => [
                'attributes' => ['amount', 'percent', 'created_at'],
            ],
			'pagination' => [
				'pageSize' => 1000,
			]
        ]),
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
				'attribute' => 'amount',
				'value' => function($data) {
					if ($data->action == \app\models\DepositHistory::ACTION_ACCRUE) {
						return $data->amount;
					} elseif ($data->action == \app\models\DepositHistory::ACTION_COMMISSION) {
                        return '-' . $data->amount;
					}
				}
			],
            'created_at:datetime',
        ],
    ]); ?>

</div>